name: microinx-ci

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  smoke:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.12"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

$1
      - name: Upgrade pip (hardening)
        env:
          PIP_DISABLE_PIP_VERSION_CHECK: "1"
          PIP_NO_PYTHON_VERSION_WARNING: "1"
        run: |
          python -m pip install -U pip

      - name: Install (editable, local-only)
        env:
          PIP_DISABLE_PIP_VERSION_CHECK: "1"
          PIP_NO_PYTHON_VERSION_WARNING: "1"
        run: |
          python -m pip install -e . --no-deps

      - name: Fast deterministic tests (explicit list)
        env:
          PYTHONUTF8: "1"
        run: |
          python -m unittest -q \
            test_microinx_engine.py \
            test_microinx_api_smoke.py \
            test_microinx_api_contract.py \
            test_microinx_demo_smoke.py

      - name: Console smoke (ephemeral port; JSON parse)
        env:
          PYTHONUTF8: "1"
          MICROINX_DEMO_PORT: "0"
        run: |
          microinx-demo > demo_out.json
          python - <<'PY'
          import json
          p = json.load(open('demo_out.json','r',encoding='utf-8'))
          assert set(p.keys()) == {'template_id','output_text','sdt','manifest'}
          assert isinstance(p['template_id'], str) and p['template_id']
          assert isinstance(p['output_text'], str) and p['output_text']
          assert set(p['sdt'].keys()) == {'pass','violations'}
          assert isinstance(p['sdt']['pass'], bool)
          assert isinstance(p['sdt']['violations'], list)
          assert set(p['manifest'].keys()) == {'version','hash_ok'}
          assert isinstance(p['manifest']['version'], str) and p['manifest']['version']
          assert isinstance(p['manifest']['hash_ok'], bool)
          print('console_smoke_ok')
          PY